FROM quay.io/openshift-cnv/container-native-virtualization-virt-launcher-rhel9@sha256:2c225da83366eef8b14021181992911eded87fa2f62b94943a2d8f9832dd2f89

USER 0
COPY rpms/ /tmp/qemu-rpms/

RUN rpm -Uvh --test /tmp/qemu-rpms/*.x86_64.rpm \
    && rpm -Uvh /tmp/qemu-rpms/*.x86_64.rpm \
    && rm -rf /tmp/qemu-rpms \
    && test "$(rpm -qa --qf '%{NAME}\t%{EPOCHNUM}:%{VERSION}-%{RELEASE}\n' \
      | awk -F '\t' '$1 ~ /^(qemu-img|qemu-kvm-common|qemu-kvm-core|qemu-kvm-device-display-virtio-gpu|qemu-kvm-device-display-virtio-gpu-pci|qemu-kvm-device-display-virtio-vga|qemu-kvm-device-usb-host|qemu-kvm-device-usb-redirect)$/ {total++; if ($2 == "17:10.1.0-17.el9_8.3") target++} END {print target+0, total+0}')" = "8 8"

LABEL io.kubevirt.qemu-rpm.advisory="RHBA-2026:28656" \
      io.kubevirt.qemu-rpm.source="qemu-kvm-10.1.0-17.el9_8.3.src.rpm"

ENTRYPOINT ["/usr/bin/virt-launcher-monitor"]
